-- mod-version:2 -- lite-xl 2.0
local syntax = require "core.syntax"

syntax.add {
  files = { "%.pony$" },
  patterns = {
    { pattern = "//.-\n",                       type = "comment"  },
    { pattern = { "/%*", "%*/" },               type = "comment"  },
    { pattern = { '"""', '"""'},                type = "comment"  },
    { pattern = { '/%g', '/', '\\' },           type = "string"   },
    { pattern = { '"', '"', '\\' },             type = "string"   },
    { pattern = "'.+'",                         type = "string"   },
    { pattern = { "`", "`", '\\' },             type = "string"   },
    { pattern = "0x[%da-fA-F]+",                type = "number"   },
    { pattern = "0b[%da-fA-F]+",                type = "number"   },
    { pattern = "-?%d+[%d%_.eE]*",              type = "number"   },
    { pattern = "-?%.?[%d]+",                   type = "number"   },
    { pattern = "^[0-9]{1,3}((_[0-9]{3})+)?$",  type = "number"   },
    { pattern = "[%+%-=/%*%^%%<>!~|&?]",        type = "operator" },
    { pattern = "[%a_][%w_]*%f[(]",             type = "function" },
    { pattern = "[%a_][%w_]*",                  type = "symbol"   },
  },
  symbols = {
    ["actor"]     = "keyword",
    ["class"]     = "keyword",
    ["trait"]     = "keyword",
    ["primitive"] = "keyword",
    ["type"]      = "keyword",
    ["interface"] = "keyword",
    ["struct"]    = "keyword",
    ["use"]       = "keyword",
    
    ["new"] = "keyword",
    ["fun"] = "keyword",
    ["be"]  = "keyword",
    
    ["compile_error"]     = "keyword",
    ["compile_intrinsic"] = "keyword",
    
    ["let"]   = "keyword",
    ["var"]   = "keyword",
    ["embed"] = "keyword",
    
    ["if"]     = "keyword",
    ["else"]   = "keyword",
    ["elseif"] = "keyword",
    ["then"]   = "keyword",
    ["end"]    = "keyword",
    ["match"]  = "keyword",
    ["for"]    = "keyword",
    ["in"]     = "keyword",
    ["do"]     = "keyword",
    ["while"]  = "keyword",
    ["while"]  = "keyword",
    ["repeat"] = "keyword",
    ["until"]  = "keyword",
    ["try"]    = "keyword",
    ["type"]   = "keyword",
    ["with"]   = "keyword",
    ["object"] = "keyword",
    ["ifdef"]  = "keyword",
    ["iftype"] = "keyword",
    ["return"] = "keyword",
    
    ["Bool"]       = "keyword",
    ["ISize"]      = "keyword",
    ["ILong"]      = "keyword",
    ["I8"]         = "keyword",
    ["I16"]        = "keyword",
    ["I32"]        = "keyword",
    ["I64"]        = "keyword",
    ["I128"]       = "keyword",
    ["USize"]      = "keyword",
    ["ULong"]      = "keyword",
    ["U8"]         = "keyword",
    ["U16"]        = "keyword",
    ["U32"]        = "keyword",
    ["U64"]        = "keyword",
    ["U128"]       = "keyword",
    ["F32"]        = "keyword",
    ["F64"]        = "keyword",
    ["String"]     = "keyword",
    ["Array"]      = "keyword",
    ["Iterator"]   = "keyword",
    ["Stringable"] = "keyword",
    ["Env"]        = "keyword",
    ["Any"]        = "keyword",
    ["Pointer"]    = "keyword",
    ["object"]     = "keyword",
    
    ["iso"] = "keyword",
    ["trn"] = "keyword",
    ["ref"] = "keyword",
    ["val"] = "keyword",
    ["box"] = "keyword",
    ["tag"] = "keyword",
    
    ["true"]      = "keyword2",
    ["false"]     = "keyword2",
    ["None"]      = "keyword2",
    ["is"]        = "keyword2",
    ["isnt"]      = "keyword2",
    ["as"]        = "keyword2",
    ["&"]         = "keyword2",
    ["|"]         = "keyword2",
    ["not"]       = "keyword2",
    ["and"]       = "keyword2",
    ["or"]        = "keyword2",
    ["xor"]       = "keyword2",
    [""]          = "keyword2",
    ["break"]     = "keyword2",
    ["continue"]  = "keyword2",
    ["where"]     = "keyword2",
    ["error"]     = "keyword2",
    ["this"]      = "keyword2",
    ["addressof"] = "keyword2",

    ["recover"]  = "keyword2",
    ["consume"]  = "keyword2",
    ["digestof"] = "keyword2",
    
    ["#read"]  = "keyword2",
    ["#send"]  = "keyword2",
    ["#share"] = "keyword2",
    ["#any"]   = "keyword2",
    ["#alias"] = "keyword2",
    
  },
}
